
outputs:
    kafka:
        bootstrapServers: kafka01.local:9092,kafka02.local:9092,kafka03.local:9092
        topic: test
logging:
    level:
        root: info
        com:
            christian: debug

